// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"achobeta-svc/backend/authz/internal/logic/account"
	"achobeta-svc/backend/authz/internal/logic/user"
	"achobeta-svc/backend/authz/internal/repo/cache"
	"achobeta-svc/backend/authz/internal/repo/casbin"
	"achobeta-svc/backend/authz/internal/repo/database"
	"achobeta-svc/backend/authz/internal/service/permission"
)

// Injectors from wire.go:

// InitServices 初始化所有服务
func InitServices() *Services {
	databaseDatabase := database.New()
	cacheCache := cache.New()
	casbinCasbin := casbin.New()
	accountPermission := account.New(databaseDatabase, cacheCache, casbinCasbin)
	userLogic := user.New(databaseDatabase, cacheCache)
	permissionServiceServer := permission.NewPermissionService(accountPermission, userLogic)
	services := newServices(permissionServiceServer)
	return services
}
