services:
  achobeta-svc-authz:
    container_name: achobeta-svc-authz
    build:
        context: .
        dockerfile: ./internal/achobeta-svc-authz/Dockerfile
    image: ccr.ccs.tencentyun.com/achobeta/achobeta-svc-authz:latest
    ports:
      - "4396:4396"
    volumes:
      - ./config:/config 
      - ./logs:/logs # 创建容器数据卷
    networks:
      - svc-networks
  achobeta-svc-api: 
    container_name: achobeta-svc-api
    build: 
      context: .
      dockerfile: ./internal/achobeta-svc-api/Dockerfile
    image: ccr.ccs.tencentyun.com/achobeta/achobeta-svc-api:latest
    ports:
      - "4397:4397"
    volumes:
    - ./config:/config 
    - ./logs:/logs
    networks:
      - svc-networks

networks:
  svc-networks: