// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	authz3 "achobeta-svc/internal/achobeta-svc-api/internal/api/authz"
	"achobeta-svc/internal/achobeta-svc-api/internal/api/health"
	authz2 "achobeta-svc/internal/achobeta-svc-api/internal/logic/authz"
	"achobeta-svc/internal/achobeta-svc-api/internal/repo/authz"
)

// Injectors from wire.go:

// 注册的服务都在这里初始化, 更新后执行make wire即可
// InitServices 初始化所有服务
func InitServices() *Apis {
	repo := authz.New()
	logic := authz2.NewLogic(repo)
	api := authz3.NewAuthApi(logic)
	healthApi := health.NewHealthApi()
	apis := newApiService(api, healthApi)
	return apis
}
