name: build status
on:
  pull_request:
    branches:
    - feature
    - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Go environment
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Install Buf
      run: GO111MODULE=on GOBIN=/usr/local/bin go install github.com/bufbuild/buf/cmd/buf@v1.33.0

    - name: lint
      run: make lint