name: build status
on:
  pull_request:
    branches:
    - feature
    - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup Go environment
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    # # Cache Go modules
    # - name: Cache Go modules
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       ~/.cache/go-build
    #       ~/go/pkg/mod
    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #     restore-keys: |
    #       ${{ runner.os }}-go-

    # # Install dependencies
    # - name: Install dependencies
    #   run: go mod download

    # Run linter (assumes you have a linter configured in your Makefile)
    - ls -al
    - run: make lint

    # # Build the Go project
    # - name: Build
    #   run: go build -o staging/task

    # # Upload artifact
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: Package
    #     path: staging